### ISSUE TITLE
invalid memoy address when trying to connect

### ISSUE THREAD

**Issue by nitay-bachrach** [allcloud-io/clisso#363]
I'm using clisso 0.14.0
`clisso version 0.14.0 (e14b558b6393fd48a4053359b15caa56a2806e65 2023-12-01T09:32:02Z)`

It happens both on Linux (Ubuntu WSL) and Windows (11).
When trying to get credentials (clisso get) I get the following error (after I provide the password, before MFA):
```
Please enter varonis-okta password: panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xc0000005 code=0x0 addr=0x38 pc=0xb8af4d]

goroutine 1 [running]:
github.com/allcloud-io/clisso/okta.Get({0xc00012a090, 0x3}, {0xc00020abb0, 0xc}, {0x0, 0x0}, {0xcbfbda, 0xa}, 0x0?)
        /Users/jonathan.vogt/Documents/code/emindsys/clisso/okta/get.go:88 +0x8ed
github.com/allcloud-io/clisso/cmd.glob..func5(0xc0001b4400?, {0xc00011d530?, 0x4?, 0xcbaada?})
        /Users/jonathan.vogt/Documents/code/emindsys/clisso/cmd/get.go:155 +0x4ba
github.com/spf13/cobra.(*Command).execute(0x11d7ae0, {0xc00011d4f0, 0x1, 0x1})
        /Users/jonathan.vogt/go/pkg/mod/github.com/spf13/cobra@v1.8.0/command.go:987 +0xaa3
github.com/spf13/cobra.(*Command).ExecuteC(0x11d8f00)
        /Users/jonathan.vogt/go/pkg/mod/github.com/spf13/cobra@v1.8.0/command.go:1115 +0x3ff
github.com/spf13/cobra.(*Command).Execute(...)
        /Users/jonathan.vogt/go/pkg/mod/github.com/spf13/cobra@v1.8.0/command.go:1039
github.com/allcloud-io/clisso/cmd.Execute({0xdc16b4?, 0x0?}, {0xdc9320?, 0x1137e38?}, {0xdc3ab0?, 0xc00006e000?})
        /Users/jonathan.vogt/Documents/code/emindsys/clisso/cmd/root.go:92 +0x10d
main.main()
        /Users/jonathan.vogt/Documents/code/emindsys/clisso/main.go:35 +0x3d
```

**Comment by bitte-ein-bit** [comment]
Does that still happen with the latest versions of clisso?

**Comment by bitte-ein-bit** [comment]
Please check 0.17.2
